CREATE TABLE IF NOT EXISTS projects (id TEXT PRIMARY KEY,name TEXT NOT NULL,category TEXT NOT NULL,description TEXT NOT NULL,location TEXT NOT NULL,photos TEXT NOT NULL,updated_at INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'draft',sort_order INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS photos (key TEXT PRIMARY KEY,filename TEXT NOT NULL,mime TEXT NOT NULL,owner TEXT NOT NULL,project_id TEXT REFERENCES projects(id),created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS settings (id TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS inquiries (id TEXT PRIMARY KEY,kind TEXT NOT NULL,name TEXT NOT NULL,phone TEXT NOT NULL,email TEXT NOT NULL,service TEXT NOT NULL,details TEXT NOT NULL,created_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS published_projects ON projects(status,sort_order,updated_at);
CREATE INDEX IF NOT EXISTS photo_project ON photos(project_id);
CREATE TABLE IF NOT EXISTS rate_limits (id TEXT PRIMARY KEY,count INTEGER NOT NULL,expires INTEGER NOT NULL);
